import os
import sys
import time

os.system("clear")
time.sleep(1)
os.system("figlet Hack Facebook")
input("ID Facebook > ")
time.sleep(10)
input("Password > ")
time.sleep(5)
os.system("clear")
os.system("figlet Hack Facebook")
print("Wait.")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Wait..")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Wait...")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Wait.")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Wait..")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Wait...")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Wait.")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Wait..")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Wait...")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Wait.")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Wait..")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Wait...")
print("Email > chiern1213@gmail.com")
os.system("clear")
os.system("figlet Hack Facebook")
print("Email > chiern1213@gmail.com")
print("Wait.")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Email > chiern1213@gmail.com")
print("Wait..")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Email > chiern1213@gmail.com")
print("Wait...")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Email > chiern1213@gmail.com")
print("Wait.")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Email > chiern1213@gmail.com")
print("Wait..")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Email > chiern1213@gmail.com")
print("Wait...")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Email > chiern1213@gmail.com")
print("Wait.")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Email > chiern1213@gmail.com")
print("Wait..")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Email > chiern1213@gmail.com")
print("Wait...")
time.sleep(2)
os.system("clear")
os.system("figlet Hack Facebook")
print("Email > chiern1213@gmail.com")
print("Password > chireen2341")
print("")
print("")
print("[*]\033[1;32;40mEnter for Exit")